apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-039d16206ce355d91
