apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: dev
type: Opaque
data:
  username: bXl1c2Vy      # base64-encoded "myuser"
  password: bXlwYXNzd29yZA==  # base64-encoded "mypassword"
